services:
  postgres:
    image: bitnami/postgresql:latest
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/bitnami/postgresql

volumes:
  pgdata:
    driver: local
